New website export
CityOfZion/cityofzion.github.io pull request #17
Opened 2017-09-15 04:28 UTC by austinhinderer

Copy of the new website found at the staging link

2017-09-15 13:42 UTC, canesin commented
@CityOfZion/council take a look at this.. 💯

2017-09-15 13:58 UTC, Ejhfast commented
is this the website on staging link here: http://fkmelrmflemrfelrkfmkermkfjn3n.s3-website-us-east-1.amazonaws.com ? 

looks great!

2017-09-15 14:22 UTC, AshRolls commented
looks good.

1. docs link in projects is 404
2. neonwallet.com is outdated (links to 0.0.4 exe)

2017-09-15 15:04 UTC, anfn101 commented
Seems like security review section was removed?

2017-09-15 15:17 UTC, canesin commented
1 - Missing http://monitor.cityofzion.io project.
2 - Links to Facebook, Twitter and Medium
3 - Standardize to CoZ .. we have voted and are phasing out COZ.

2017-09-17 20:58 UTC, austinhinderer commented
@AshRolls Will fix links.
@anfn101 Was directed to remove this section as there was no page to link to yet.
@canesin I will update the CoZ copy in the content. For the other two, are they just content suggestions or is there something missing from the mockups that I need to add? If not we need to circle back with hamster and get fresh assets.

2017-09-17 21:01 UTC, austinhinderer commented
@AshRolls I pulled that link off of the current website. Is there a correct target this should point at?

2017-09-17 23:08 UTC, austinhinderer commented
Posted some responsive updates from hamster, as well as fixed a few instances of COZ -> CoZ.

- I need a place to link to for the documentation
- We'll follow up with security review once the content is ready
- Hamster is going to follow up with me on monitor.cityofzion.io

Hamster has approved the current staging link from a design perspective. Let me know if you see any problems with what we have, otherwise we should push out what we have and begin iterative improvements (after updating the broken docs link).

2017-09-17 23:19 UTC, anfn101 commented
You can link here for docs: https://github.com/neo-project/docs

2017-09-17 23:33 UTC, austinhinderer commented
Updated the link

2017-09-18 20:32 UTC, canesin requested changes

2017-09-18 20:32 UTC, canesin commented on manifest.json
> +<<<<<<< HEAD
Missing conflict resolution here

2017-09-18 20:45 UTC, Nat1988 commented
We need copy for the NEO Monitor - can anyone provide this please?

2017-09-18 20:46 UTC, canesin commented
@Nat1988 https://github.com/CityOfZion/neo-mon ?

2017-09-18 20:47 UTC, Nat1988 commented
Perfect!

2017-09-19 06:30 UTC, austinhinderer commented on manifest.json
> +<<<<<<< HEAD
Thanks, removed.

2017-09-19 06:31 UTC, austinhinderer commented
- Added a link to NeoMon
- Added social media links
- Corrected merge conflict

2017-09-19 14:24 UTC, canesin approved these changes

2017-09-19 14:24 UTC, merged

2017-09-19 14:39 UTC, canesin commented
I merged so we can move forward.. but where is the sources for the uncompiled website ? do you have instructions on how to edit ? ..
Also the slack link should be https://slack.cityofzion.io

2017-09-19 17:26 UTC, austinhinderer commented
The source is in a branch on the Visual Identity repo. I suggest we break it into its own repo for easy CI in the future.

I put together a PR with the change for the slack link: https://github.com/CityOfZion/cityofzion.github.io/pull/19